#!/bin/bash
# On Controller

#create password
```
for i in ROOT_DBPASS ADMIN_PASS CINDER_DBPASS CINDER_PASS DASH_DBPASS  \
DEMO_PASS GLANCE_DBPASS GLANCE_PASS KEYSTONE_DBPASS NEUTRON_DBPASS NEUTRON_PASS \
NOVA_DBPASS NOVA_PASS  RABBIT_PASS; do echo "export $i=$(openssl rand -hex 10)" >> password.txt ;done
```
#set ~/.bash_profile
```
vi ~/.bash_profile

source /root/password.txt
echo $ROOT_DBPASS
alias db="mysql -uroot -p$ROOT_DBPASS"
```

