## Install Services
```
19:CONFIG_MARIADB_INSTALL=y
22:CONFIG_GLANCE_INSTALL=y
25:CONFIG_CINDER_INSTALL=y
29:CONFIG_MANILA_INSTALL=y
32:CONFIG_NOVA_INSTALL=y
36:CONFIG_NEUTRON_INSTALL=y
39:CONFIG_HORIZON_INSTALL=y
42:CONFIG_SWIFT_INSTALL=y
45:CONFIG_CEILOMETER_INSTALL=y
49:CONFIG_AODH_INSTALL=y
53:CONFIG_GNOCCHI_INSTALL=y
57:CONFIG_SAHARA_INSTALL=n
60:CONFIG_HEAT_INSTALL=y
63:CONFIG_TROVE_INSTALL=y
67:CONFIG_IRONIC_INSTALL=n
71:CONFIG_CLIENT_INSTALL=y
80:CONFIG_NAGIOS_INSTALL=y
823:CONFIG_LBAAS_INSTALL=y
827:CONFIG_NEUTRON_METERING_AGENT_INSTALL=y
1162:CONFIG_HEAT_CLOUDWATCH_INSTALL=n
1166:CONFIG_HEAT_CFN_INSTALL=y

```
## Set M2 Network
```
CONFIG_NEUTRON_ML2_TYPE_DRIVERS=vxlan,flat,local
CONFIG_NEUTRON_ML2_TENANT_NETWORK_TYPES=vxlan,vlan,local
CONFIG_NEUTRON_ML2_VLAN_RANGES=physnet1:1:1000
CONFIG_NEUTRON_OVS_BRIDGE_MAPPINGS=extnet:br-ex,physnet1:br-eth2
CONFIG_NEUTRON_OVS_BRIDGE_IFACES=br-ex:eth1,br-eth2:eth2
```